function __profileSort__(a,b){
    if (a.split(".").length > b.split(".").length) return -1;
    if (a.split(".").length < b.split(".").length) return 1;
    return 0;
}

function __templateForView__(view) {
    var selector = view.template+"_"+view.viewType;
    var profile = "muon";
    view.constructor.profiles = view.constructor.profiles.sort(__profileSort__);
    for(var i in view.constructor.profiles){
        if (m.hasProfile(view.constructor.profiles[i]))
        {
            profile = view.constructor.profiles[i];
            break;
        }
    }
    selector = "script#"+selector+"_template";
    selector += "[type='text/muon-template'][data-pack='"+view.package+"']";
    selector += "[data-profile='"+profile+"']";
    return $(selector)[0];
};

function __attrsParser__(attrs){
    var ret = {};
    var tempAttrs = attrs || "";
    tempAttrs = tempAttrs.split(";");
    for(var i in tempAttrs){
        var attr = tempAttrs[i].split(":");
        if (attr.length != 2) continue;
        ret[attr[0].replace(/^\s+/,"").replace(/\s+$/,"")] = attr[1].replace(/^\s+/,"").replace(/\s+$/,"");
    }
    return ret;
}

var __procProjection__ = {
    collection: function(el,collectionName,projection){
        var collAttrs = __attrsParser__(el.dataset["contextAttrs"]);
        if (typeof collAttrs.model === "string"){
            if (!(collAttrs.model in m.models)) throw Error("Unknown model: "+collAttrs.model);
            collAttrs.model = m.models[collAttrs.model];
        }
        if (projection instanceof m.Collection) return _.extend(projection,collAttrs);
        var Collection = m.collections[collectionName] || m.Collection;
        var dfd = $.Deferred();
        if (_.isArray(projection)){
            var coll = new Collection([],collAttrs);
            for(var i in projection){
                var el = projection[i];
                if (typeof el == "string" || typeof el == "number" || _.isObject(el)){
                    coll.add(new Collection.prototype.model(el));
                }
            }
            return coll;
        }
        if (projection === undefined){
            var coll = new Collection([],collAttrs);
            coll.fetch();
            return coll;
        }
        _.defer(dfd.reject,"Wrong projection type");
        return dfd.promise();
    },
    model: function(el,modelName,projection){
        var modelAttrs = __attrsParser__(el.dataset["contextAttrs"]);
        modelAttrs.__autoGenerated__ = true;
        if (projection instanceof m.Model) return _.extend(projection,modelAttrs);
        if (!(modelName in m.models) && !(modelName in this.m.models)) throw Error("Unknown model name: "+modelName);
        var Model = m.models[modelName] || this.m.models[modelName];
        if (el.dataset.contextAttrs) Model = Model.extend(modelAttrs);
        var dfd = $.Deferred();
        if ((typeof projection == "string" || typeof projection == "number" || projection) && el.dataset.modelId)
            throw Error("You shouldn't use both projection variable and model Id attribute in one view simultaneously.");
        if (typeof projection == "string" || typeof projection == "number" ){
            _.defer(dfd.resolve,new Model(projection,{forceSync: true}));
            return dfd.promise();
        }
        if (typeof el.dataset.modelId == 'string'){
            _.defer(dfd.resolve,new Model(el.dataset.modelId,{forceSync: true}));
            return dfd.promise();
        }
        if (_.isObject(projection) || projection === undefined){
            return new Model();
        }
        _.defer(dfd.reject,"Wrong projection type");
        return dfd.promise();
    },
    layout: function(el,non,projection){
        return _.extend(projection,__attrsParser__(el.dataset["contextAttrs"]));
    },
    stack: function(el,non,projection){
        return _.extend(projection,__attrsParser__(el.dataset["contextAttrs"]));
    },
    widget: function(el,non,projection){
        return _.extend(projection,__attrsParser__(el.dataset["contextAttrs"]));
    }
};

function __getViewNameByType__(viewType,viewName,_contextName,pack,recursive){
    pack = pack || __basePackage__;
    _contextName = _contextName || "";
    pack = pack || __basePackage__;
    try{
        var View = null;
        if (!View && !recursive) View = m.packages[pack].views[viewType][viewName];
        if (!View && (viewType == "model" || viewType == "collection") && _contextName){
            var contextName = _contextName.replace(/:/g,".").split("."), _viewName = viewName;
            for(var i in contextName) _viewName = _viewName.replace(RegExp("_"+contextName[i]+"$"),"");
            if (_viewName != viewName){
                return __getViewNameByType__(viewType,_viewName,_contextName,pack,true);
            }
        }
        if (!View && (viewType == "model" || viewType == "collection") && _contextName){
            var contextName = _contextName.replace(/:/g,".").split(".").reverse().join("_");
            while(!m.packages[pack].views[viewType][viewName+"_"+contextName] && contextName.length != 0){
                var prevName = contextName;
                contextName = contextName.replace(/^[a-zA-Z0-9]+_/,"");
                if (prevName == contextName) contextName = "";
            }
            View = m.packages[pack].views[viewType][viewName+(contextName?"_":"")+contextName];
        }
        if (!View && recursive) View = m.packages[pack].views[viewType][viewName];
        if (!View) throw Error("not exists");
        return View;
    }
    catch(e){
        if (_contextName.indexOf(":") == -1) throw Error("Wrong view name:"+viewName+"_"+viewType+":"+_contextName+":"+ e.message);
        else return __getViewNameByType__(viewType,viewName,_contextName.substr(_contextName.indexOf(":")+1),pack,true);
    }
};

function __checkPresenceInDom__(el){
    while (el.parentElement) {
        if (el.parentElement == document.body) return true;
        else el = el.parentElement;
    }
    return false;
}

function __getParentMuonView__(el){
    do {
        if (el.muonView instanceof m.View) return el;
        else el = el.parentElement;
    }
    while (el.parentElement);
    return null;
}


//__onReady__.push(function(){
//    var obs = window.MutationObserver || window.WebKitMutationObserver;
//    if (!obs) return;
//    function __changeProc__(record){
//        for(var i = 0, len = record.length; i < len; i++){
//            var rec = record[i];
//            console.log(rec);
//        }
//    }
//    new obs(__changeProc__).observe(document.body,{subtree:true,attributes:true,attributeFilter:[
//        "data-model-view",
//        "data-collection-view",
//        "data-layout-view",
//        "data-stack-view",
//        "data-widget-view",
//        "data-model-attr",
//        "data-model-set",
//        "data-model-get",
//        "data-attr-type",
//        "data-context",
//        "data-context-attrs",
//        "data-view-attrs",
//        "data-projection"
//    ]});
//
//    new obs(__changeProc__).observe(document.body,{subtree:true,childList:true});
//});


function __insertView__(el,viewType,pack,parentView){
    var _this = this;
    if (!(pack in m.packages)){
        m.requirePack(pack,function(){
            __insertView__.apply(_this,[el,viewType,pack,parentView]);
        });
        return;
    }
    var projection = el.dataset["projection"];
    var viewName = el.dataset[viewType+"View"];
    if (viewName == "data-"+viewType+"-view") viewName = "";
    if (projection){
        var mPlugin = m.getProjection(projection)?m:parentView.m;
        $(mPlugin).one("projection_updated."+projection, function(){
            if (!__checkPresenceInDom__(el)) return;
            __insertView__.apply(_this,[el,viewType,pack,parentView]);
        });
        $(mPlugin).one("projection_removed."+projection,function(){
            if (el.muonView instanceof m.View) el.muonView.remove();
            $(mPlugin).one("projection_updated."+projection, function(){
                if (!__checkPresenceInDom__(el)) return;
                __insertView__.apply(_this,[el,viewType,pack,parentView]);
            });
        });
        projection = mPlugin.getProjection(projection);
        if (projection === undefined) return;
    }
    setTimeout(function(){
        if (el.muonView instanceof m.View){
            el.muonView.remove();
            delete el.muonView;
        }
        try{
            $.when(__procProjection__[viewType].call(_this,el,el.dataset["context"],projection)).
                then(function(context){
                    try {
                        context = context || {};
                        var View = __getViewNameByType__(viewType,viewName,context.modelName,pack);
                        var viewAttrs = __attrsParser__(el.dataset["viewAttrs"]);
                        viewAttrs.__autoGenerated__ = true;
                        viewAttrs.package = pack;
                        viewAttrs.plugin = _this.plugin;
                        new (View.extend(viewAttrs))(context,el);
                    }
                    catch(e){
                        console.log(parentView.template,el);
                        console.debug(e.stack);
                    }
                });
        }
        catch(e){
            console.log(parentView.template,el);
            console.debug(e.stack);
        }
    },0);

    this.innerHTML = "";
}

function __getTranslation__(el){
    var translation = this.pack().translation[this.template+"_"+this.viewType+":"+el.dataset.tr];
    if (m.isDebug() && !translation) {$(el).addClass("untranslated");}
    else {$(el).removeClass("untranslated");}
    return translation || (m.isDebug()?"untranslated":"");
}

__b__.View.extend = function(obj,common){
    var viewType = (_.isString(obj.viewType))?obj.viewType:this.prototype.viewType;
    obj.package = obj.package || __currentPackage__ || this.prototype.package || __basePackage__;
    obj.plugin = obj.plugin || __currentPlugin__  || this.prototype.plugin || "";
    obj.m = __registerPlugin__(obj.plugin);
    var newView = __viewBackboneExtend__.apply(this,arguments);
    if (obj.__autoGenerated__) return newView;
    var template = newView.prototype.template;
    if (typeof template == "string"){
        if (!_.isObject(m.packages[__currentPackage__].views[viewType]))
            m.packages[__currentPackage__].views[viewType] = {};
        m.packages[__currentPackage__].views[viewType][template] = newView;
    }
    else {
        if (!_.isArray(m.packages[__currentPackage__].viewsUnnamed[viewType]))
            m.packages[__currentPackage__].viewsUnnamed[viewType] = [];
        m.packages[__currentPackage__].viewsUnnamed[viewType].push(newView);
    }
    newView.prototype.super = this.prototype.constructor.prototype;
    newView.profiles = [];
    if (viewType && !m.baseViews[viewType]) m.baseViews[viewType] = newView;
    return newView;
};

function __render__(){
    var _this = this;
    var tagName = this.tagName || "div";
    var $el = $("<"+tagName+" />");
    this.__renderTemplate__($el[0]);
    if (this.el && this.el.muonView == this){
        this.el.innerHTML = "";
        $(this.el).append($el.children());
    }
    else this.el = $el[0];
    this.$el = $(this.el);
    this.$ = _.bind(this.$el.find,this.$el);
    this.postTemplateRender && this.postTemplateRender();
    this.undelegateEvents();
    this.delegateEvents();
    this.$el.addClass([this.className,this.viewType,"block"].join(" "));
    this.el.muonView = this;
    this.el.dataset.muon = this.template?this.template+"_"+this.viewType:"";
    this.el.dataset.pack = this.package;
    __renderFocus__.call(this);
    __renderDependencySrc__.call(this);
    __renderDataRoutes__.call(this);
    __renderTranslation__.call(this);
    __renderDebugLabels__.call(this);
    this.__set__ && this.__set__();
    for(var i in m.baseViews){
        var $els = this.$el.find("*[data-"+i+"-view]");
        $els.each(function(){
            __insertView__.call(_this,this,i,this.dataset.pack || _this.package,_this);
        });
    }
    this.rendered && this.rendered($el);
    // Render called in the same flow constructor was launched
    _.defer(_.bind(this.trigger,this),"rendered");
}

function __renderDebugLabels__(){
    if (!m.isDebug() || this.debugLabel) return;
    this.debugLabel = $("<div data-debug/>").text(this.package+":"+this.viewType+":"+(this.template||""))
        .appendTo(this.el);
    this.debugLabel.click(function(){
        $(this).toggleClass("pinned");
        $(this).parent().toggleClass("pinned");
    });
    __renderTranslation__.call(this);
}

function __renderTranslation__(){
    var _this = this;
    var innerTrs =  this.$el.find("*[data-muon] *[data-tr]");
    this.$el.find("*[data-tr]").not(innerTrs).each(function(){
        try{ this.innerHTML = __getTranslation__.call(_this,this); }
        catch(e){ console.log(e); }
        if (!m.isDebug()) return;
        this.debugLabel = $("<div data-debug/>").text(_this.package+":"+_this.template+"_"+_this.viewType+":"+this.dataset.tr)
            .appendTo(this);
    });
}

function __renderDataRoutes__(){
    var _this = this;
    this.$el.find("a[data-route]").each(function(){
        var route = this.dataset.route;
        var packName = this.dataset.pack || _this.package;
        if (!(packName in m.packages)) return;
        if (m.packages[packName].routerPath){
            route = (m.packages[packName].routerPath+"/"+route).replace(/\/{2,}/g,"/");
            route = route.replace(/\^|\$/g,"");
        }
        $(this).attr("href",route)
            .attr("data-pack",packName);
    });
}

function __renderDependencySrc__(){
    var _this = this;
    var innerSrc =  this.$el.find("*[data-muon] *[data-src]");
    this.$el.find("*[data-src]").not(innerSrc).each(function(){
        this.src = "/pack_src/"+_this.package+"/"+this.dataset["src"]+"?muon";
    });
    if (__staticApp__)
        ["src","href"].map(function(a){
            $("["+a+"]",_this.el).each(function(){
                if (!/^\/\//.test($(this).attr(a))) $(this).attr(a,$(this).attr(a).replace(/^\//,""));
            });
        });
}

function __renderFocus__(){
    var counter = 1;
    this.$("[data-focus]").each(function(){
        $(this).attr("tabindex",counter++);
    });
}

function __removeInnerViews__(){
    this.$("[data-muon]").each(function(){
        if (this.muonView instanceof m.View) this.muonView.remove();
    });
}

m.View = __b__.View.extend({
    one: __b__.View.prototype.once,
    tagName: "div",
    toString: function(){
        return this.package+":"+this.viewType+":"+this.template;
    },
    initialize:function(context,_el_){
        if (!isFinite(this.__view_index__)) this.__view_index__ = __views__.push(this) - 1
        else console.log("Already in: "+this.__view_index__);
        this.context = context || {};
        if (_el_ && _el_.nodeName) {
            this.__forcedElement__ = true;
            this.el = _el_;
            this.el.muonView = this;
        }
        if (typeof this.init == "function") this.init.apply(this,arguments);
        __render__.call(this);
    },
    __renderTemplate__: function(el){
        if (this.template){
            var template = __templateForView__(this);
            if (!template) return;
            $(el).jqoteapp(template.innerHTML,this.context);
        }
    },
    render: undefined,
    remove: function(){
        if (this.__removed) return;
        __removeInnerViews__.call(this);
        if (this.__forcedElement__){
            this.undelegateEvents();
            this.$el.children().remove();
            $(this.el).removeAttr("data-muon");
        }
        else this.el.remove();
        __views__.splice(this.__view_index__,1);
        delete this.el.muonView;
        this.stopListening();
        this.__removed = true;
        this.trigger("removed");
    },
    reload: function(){
        if (this.__reload_flag__) return;
        this.__reload_flag__ = true;
        var _this = this;
        _.defer(function(){
            __removeInnerViews__.call(_this);
            __render__.call(_this);
            _this.__reset__ && _this.__reset__();
            _this.trigger("reloaded");
            _this.__reload_flag__ = false;
        })

    },
    pack: function(){return m.packages[this.package];},
    surrogate: function(){return m.packages[this.package].packageObject.surrogate;},
    focus: function(el){
        var el = this.$("[data-focus='"+el+"']");
        if (!el.length) return;
        el.focus();
    },
    trigger: function(){
        console.log(this.toString(),arguments);
        this.$el.trigger.apply(this.$el,arguments);
        __b__.View.prototype.trigger.apply(this,arguments);
    }
});